### ISSUE TITLE
Release Candidate 1.1.0 RC1 

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#186]
### Summary
Build the new release candidate of "ssi-credential-issuer" (see components below) and deploy to association integration env.
Execute the release process in the eclipse-tractusx organisation.
Branch: Release Branch

### Tasks:

- [x]  changelog created
- [x]  release ssi-credential-issuer (version bump, changelog, update readme, release new helm chart, merge release branch)
- [x]  provide successive release branch (tractusx und ng-forks) for release closure
- [x]  change base of open PRs
- [x]  user info/association info
- [x]  deploy to integration environment
- [x]  inform team members of the deployment status

Ideally wait for the following two PRs to get merged

- https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/192
- https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/193

**Comment by jjeroch** [comment]
@evegufy content updated
